<a href="https://colab.research.google.com/github/rupanshi1627-create/90-days-DSA_using-python/blob/main/150_NEETCODE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#first we try with the brute force obe by one jayenge
#because we tracing each and every element so time and space complexity is more
#time complexity For n elements, the number of comparisons is roughly:o(O(n²)) as we have loop in loop nxn
nums=[1,2,3,7,8,1]
is_duplicate=False

for i in range(len(nums)):
  for j in range(i+1,len(nums)):
    if nums[i]==nums[j]:
      is_duplicate=True
      break

  if is_duplicate:
    break

print(is_duplicate)

#now we will try optimising it-- we have sets for that
nums=[1,2,3,7,8,1]
seen=set()

for num in nums:
  if num in seen:
    print(True)
    break

  seen.add(num)
else:
    print(False)


True
True


In [ ]:
#best time to seel and buy stockes
prices=[7,2,5,3,4,6,8]
max_profit=0

for i in range(len(prices)):
  for j in range(1+1, len(prices)):
    profit=prices[j]-prices[i]
  if profit>max_profit:
    max_profit=profit

print(max_profit)
## optimized version
def maxProfit(prices):
    min_price = prices[0]
    max_profit = 0
    prices = [7, 1, 5, 3, 6, 4]


    for price in prices:
        if price < min_price:
            min_price = price

        profit = price - min_price

        if profit > max_profit:
            max_profit = profit

    return max_profit

print(maxProfit(prices))

6
5


In [ ]:
# This code snippet finds a missing number in a sequence of integers.
# It assumes the sequence should be continuous starting from 0, with exactly one number missing.

# Define the list of numbers where one is missing
numbers=[0,1,3]

# Initialize a variable to store the missing value
missing_value=0

# Iterate from 0 up to (and including) the length of the 'numbers' list
# For example, if numbers has 3 elements, it iterates from 0 to 3 (0, 1, 2, 3)
for i in range(len(numbers)+1):
  # Check if the current number 'i' is NOT present in the 'numbers' list
  if i not in numbers:
    # If 'i' is not found, it is the missing number
    missing_value=i
    # We can break here since we assume only one number is missing
    break

# Print the identified missing value
print(missing_value)

# Optimized version: This approach uses mathematical properties to find the missing number efficiently.
class Solution:
    def missingNumber(self, nums: list[int]) -> int:
        # Calculate the sum of numbers that *should* be present in the complete sequence.
        # If 'nums' has 'n' elements, the complete sequence (0 to n) has 'n+1' elements.
        # The sum of numbers from 0 to n is given by the formula: n * (n + 1) / 2.
        # Here, 'len(nums)' represents 'n' for the highest expected value.
        expected_sum = len(nums) * (len(nums) + 1) // 2

        # Initialize a variable to store the actual sum of numbers in the given list.
        actual_sum = 0

        # Iterate through each number in the input list 'nums'.
        for num in nums:
            # Add each number to the 'actual_sum'.
            actual_sum += num

        # The difference between the 'expected_sum' and 'actual_sum' will be the missing number.
        return expected_sum - actual_sum


2


In [ ]:
#Numpy
import numpy as np
number=[1,5,6,7,8,9]

numpy_num=-np.array(number)

print("what is the data type:",numpy_num.dtype)
print("what is the size of the numpy array:",numpy_num.shape)
marks_table = np.array([[45, 67, 23], [89, 56, 78]])
print("2D Array:\n", marks_table)
print("2D Shape:", marks_table.shape)




what is the data type: int64
what is the size of the numpy array: (6,)
2D Array:
 [[45 67 23]
 [89 56 78]]
2D Shape: (2, 3)


In [ ]:
#valid palindrome
import re
s = "A man, a plan, a canal: Panama"

new_clean=re.sub(r'[^a-zA-Z0-9]','',s).lower()
print(new_clean)
left=0
right=len(new_clean)-1
is_palindrome=True

while left<right:
  if new_clean[left]==new_clean[right]:
    is_palindrone=True
    left+=1
    right-=1
  else:
    is_palindrome=False
print(is_palindrome)



amanaplanacanalpanama
True


### Corrected `isPalindrome` Method

Below is the corrected `Solution` class with the `isPalindrome` method. Notice that:

1.  The typo `is_palindrone` is fixed to `is_palindrome`.
2.  The `return is_palindrome` statement is moved to be *outside* the `while` loop, but *inside* the `isPalindrome` method. This way, the loop checks all characters, updates the `is_palindrome` flag if a mismatch is found, and then the function returns the final value of the flag after the loop has completed.

In [ ]:
import re

class Solution:
    def isPalindrome(self, s: str) -> bool:
        new_clean = re.sub(r'[^a-zA-Z0-9]', '', s).lower()
        left = 0
        right = len(new_clean) - 1
        is_palindrome = True # Initialize to True, assuming it's a palindrome until proven otherwise

        while left < right:
            if new_clean[left] == new_clean[right]:
                left += 1
                right -= 1
            else:
                is_palindrome = False # Set to False if a mismatch is found
                break # No need to continue checking, it's not a palindrome

        return is_palindrome # Return the final result after the loop

# Demonstration
solution_instance = Solution()

# Test cases
str1 = "A man, a plan, a canal: Panama"
print(f"'{str1}' is a palindrome: {solution_instance.isPalindrome(str1)}")

str2 = "race a car"
print(f"'{str2}' is a palindrome: {solution_instance.isPalindrome(str2)}")

str3 = "level"
print(f"'{str3}' is a palindrome: {solution_instance.isPalindrome(str3)}")

str4 = "Madam"
print(f"'{str4}' is a palindrome: {solution_instance.isPalindrome(str4)}")


'A man, a plan, a canal: Panama' is a palindrome: True
'race a car' is a palindrome: False
'level' is a palindrome: True
'Madam' is a palindrome: True


In [5]:
#MOST OPTIized version of this valid palindrome question

s = "A man, a plan, a canal: Panama"
left=0
right=len(s)-1
is_palindrome=True
s_clean=0
for char in s:
  if char.isalnum():
    s_clean=s.lower()
    print(s_clean)

  while left<right:
    if s_clean[left]==s_clean[right]:
      left+=1
      right-=1
      is_palindrome=True
    else:
      is_palindrome=False
print(is_palindrome)

a man, a plan, a canal: panama


KeyboardInterrupt: 

In [11]:
#.dtype and type()

import numpy as np
s=[2,3,4,5]
print("Type of s (list):", type(s))

np_s=np.array([s])
print(np_s)
print("Type of np_s (ndarray):", type(np_s))
print("Data type of elements in np_s:", np_s.dtype)

# Corrected way to create a 2D numpy array
next_d=np.array([[1,2,3,4],[8,2,3,4],[2,0,9,8]])
print("\n2D Array next_d:\n", next_d)
print("Data type of elements in next_d:", next_d.dtype)

Type of s (list): <class 'list'>
[[2 3 4 5]]
Type of np_s (ndarray): <class 'numpy.ndarray'>
Data type of elements in np_s: int64

2D Array next_d:
 [[1 2 3 4]
 [8 2 3 4]
 [2 0 9 8]]
Data type of elements in next_d: int64


In [15]:
#np.arange-- same as list range jaisa kaam
import numpy as np
np.arange(1,13) #1 se 12 tak element print krega and last vala excluded hi rhega.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
##reshape with np.arange
np.arange(1,13).reshape(3,4)
#the product of both the reshape element should be equal to the element present in the array
#first one is row and second one is column


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
#np.identity matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])